# Generated by Django 5.2.6 on 2025-09-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(choices=[('futsal shoes', 'Futsal shoes'), ('football shoes', 'Football shoes'), ('socks', 'Socks')], default='football shoes', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
